#!/bin/bash
# SRA Download Script
# Generated by scAgent on 2025-07-18 21:10:36
# 
# This script downloads 5 SRA datasets suitable for sc-eQTL analysis
# 
# Prerequisites:
# - SRA Toolkit installed (https://github.com/ncbi/sra-tools)
# - Sufficient disk space (estimate ~1-10GB per dataset)
# 
# Usage:
# chmod +x download_human_scrna.sh
# ./download_human_scrna.sh

set -e  # Exit on error
set -u  # Exit on undefined variable

echo "Starting SRA download process..."
echo "Target directory: ./downloads"
echo "Number of datasets: 5"
echo ""

# Create output directory
mkdir -p ./downloads

# Download commands

echo "Processing dataset 1/4..."
prefetch SRR10000199 -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 1 downloaded successfully"
else
    echo "❌ Dataset 1 download failed"
fi

echo "Processing dataset 2/4..."
fastq-dump --split-files --gzip ./downloads/SRR10000199/SRR10000199.sra -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 2 downloaded successfully"
else
    echo "❌ Dataset 2 download failed"
fi

echo "Processing dataset 3/4..."
prefetch SRR10000198 -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 3 downloaded successfully"
else
    echo "❌ Dataset 3 download failed"
fi

echo "Processing dataset 4/4..."
fastq-dump --split-files --gzip ./downloads/SRR10000198/SRR10000198.sra -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 4 downloaded successfully"
else
    echo "❌ Dataset 4 download failed"
fi

echo "Processing dataset 5/4..."
prefetch SRR10000197 -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 5 downloaded successfully"
else
    echo "❌ Dataset 5 download failed"
fi

echo "Processing dataset 6/4..."
fastq-dump --split-files --gzip ./downloads/SRR10000197/SRR10000197.sra -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 6 downloaded successfully"
else
    echo "❌ Dataset 6 download failed"
fi

echo "Processing dataset 7/4..."
prefetch SRR10000191 -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 7 downloaded successfully"
else
    echo "❌ Dataset 7 download failed"
fi

echo "Processing dataset 8/4..."
fastq-dump --split-files --gzip ./downloads/SRR10000191/SRR10000191.sra -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 8 downloaded successfully"
else
    echo "❌ Dataset 8 download failed"
fi

echo "Processing dataset 9/4..."
prefetch SRR10000179 -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 9 downloaded successfully"
else
    echo "❌ Dataset 9 download failed"
fi

echo "Processing dataset 10/4..."
fastq-dump --split-files --gzip ./downloads/SRR10000179/SRR10000179.sra -O ./downloads
if [ $? -eq 0 ]; then
    echo "✅ Dataset 10 downloaded successfully"
else
    echo "❌ Dataset 10 download failed"
fi

echo ""
echo "Download process completed!"
echo "Check ./downloads for downloaded files"
